### ISSUE TITLE
Bring new brand colors into Protocol 

### ISSUE THREAD

**Issue by ejregithub** [mozilla/protocol#291]
| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 2 |
| SEO | |
| ANA | |
| DES | 4 |
| COPY | |

Description, good enough that reading the card 1 month from now, you still know what it means.

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] Incorporates the new branding
- [ ] Guidelines for accessibility

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Deprecating colors that are currently used in the system

#### Tasks
- [x] Define the new brand palette
- [ ] Test for accessibility
- [ ] Write guidelines

**Comment by vincejoyiv** [comment]
Latest brand palette is here https://share.goabstract.com/038b97ac-a908-460f-865a-553d54e1d3b9

**Comment by alexgibson** [comment]
Fixed in https://github.com/mozilla/protocol-tokens/pull/34
