### ISSUE TITLE
Bring new brand assets into Protocol

### ISSUE THREAD

**Issue by ejregithub** [mozilla/protocol#292]
| Estimates |  |
| ------------- | ------------- |
| TL | |
| PM | |
| ENG | 3 |
| SEO | |
| ANA | |
| DES | 4 |
| COPY | |

Part of the new branding includes an updated set of icons. We need to make sure those icons fit within the system we established for the nav. 

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [x] Icons fulfill the needs of the navigation and other existing components
- [x] Guidelines are written so new icons can be created and added to this set
- [x] Icons are added to the Protocol Sketch file

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] Having to revisit icons because the design isn't consistent with past icons or in product icons

#### Tasks
- [x] Update/ Add new icons to our existing icon set
- [x] Update the Protocol tokens assets repository
- [ ] Update the Protocol to consume new assets

**Comment by ejregithub** [comment]
@michaelmccombie - can you please let me know status here, if you project to complete this before the new sprint starts on Monday the 4th?

**Comment by michaelmccombie** [comment]
The new icons have been uploaded to the protocol-assets repository and added to the Sketch file.

**Comment by stephaniehobson** [comment]
@alexgibson could you please publish a new npm version of the assets repo?

**Comment by stephaniehobson** [comment]
Reopening until Protocol has been updated to consume the new nmp package.

**Comment by alexgibson** [comment]
Done https://www.npmjs.com/package/@mozilla-protocol/assets 👍

**Comment by stephaniehobson** [comment]
The white versions of the follow icons were in used and removed in the 2.0.0 version of the assets:

- menu
- close
- expand

@michaelmccombie Did you have something in mind for how to generate the white versions when you removed them?

**Comment by stephaniehobson** [comment]
We should be able to generate white versions, there's no need to have the icons in the package twice, one in each colour.

**Comment by stephaniehobson** [comment]
I'm going to call this done in #479
