### ISSUE TITLE
Write Design System PRD for Fx interface elements

### ISSUE THREAD

**Issue by wboucherfischer** [mozilla/protocol#406]
## Description
Write Design System PRD for adding Fx interface elements to Protocol

---

#### :yellow_heart: Success Criteria :yellow_heart:
- [ ] PRD written
- [ ] Sketch library and symbols created
- [ ] Review by Team

#### :heavy_exclamation_mark: Risks :heavy_exclamation_mark:
- [ ] We design a new look and feel for Fx or Mozilla.
- [ ] Designers don't talk to developers and developers don't talk to designers

#### Tasks
- [ ] Conceptualize design system and explore
- [ ] Write requirements in PRD

See PRD: [PRD](https://docs.google.com/document/d/1NgIKryJ0dCoPOGqE5A6rFgjDomd-PuVuLulFhPkN3N8/edit)

**Comment by hoosteeno** [comment]
Issue moved to [mozilla/bedrock #7444](https://github.com/mozilla/bedrock/issues/7444) via [**ZenHub**](https://www.zenhub.com/)
