### ISSUE TITLE
Epic: New components to support brand refresh

### ISSUE THREAD

**Issue by stephaniehobson** [mozilla/protocol#954]
The new designs for the website have some new components. This issue is to collect those additions in one place.
```[tasklist]
### Tasks
- [ ] https://github.com/mozilla/protocol/issues/960
- [ ] https://github.com/mozilla/protocol/issues/961
- [ ] https://github.com/mozilla/protocol/issues/962
- [ ] https://github.com/mozilla/protocol/issues/963
- [ ] https://github.com/mozilla/protocol/issues/964
- [ ] https://github.com/mozilla/protocol/issues/965
- [ ] https://github.com/mozilla/protocol/issues/966
- [ ] https://github.com/mozilla/protocol/issues/967
- [ ] https://github.com/mozilla/protocol/issues/968
- [ ] https://github.com/mozilla/protocol/issues/969
- [ ] https://github.com/mozilla/protocol/issues/970
```
